services:
  - type: web
    name: genesys-render-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: API_KEY
        sync: false
